require("dotenv").config();
const express=require("express"),path=require("path"),fs=require("fs"),crypto=require("crypto"),helmet=require("helmet"),multer=require("multer");
const app=express(); const PORT=process.env.PORT||3000; const ROOT=__dirname,DATA_DIR=path.join(ROOT,"data"),UPLOAD_DIR=path.join(ROOT,"uploads"),PRODUCTS_FILE=path.join(DATA_DIR,"products.json");
fs.mkdirSync(DATA_DIR,{recursive:true});fs.mkdirSync(UPLOAD_DIR,{recursive:true});if(!fs.existsSync(PRODUCTS_FILE))fs.writeFileSync(PRODUCTS_FILE,"[]");
app.set("view engine","ejs");app.set("views",path.join(ROOT,"views"));app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));app.use(express.urlencoded({extended:true}));app.use(express.json());app.use("/assets",express.static(path.join(ROOT,"public")));
const storage=multer.diskStorage({destination:(_r,_f,cb)=>cb(null,UPLOAD_DIR),filename:(_r,f,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(8).toString("hex")}${path.extname(f.originalname).toLowerCase()}`)});
const upload=multer({storage,limits:{fileSize:8*1024*1024},fileFilter:(_r,f,cb)=>{const ok=["image/jpeg","image/png","image/webp"].includes(f.mimetype);cb(ok?null:new Error("Only JPG, PNG and WEBP images are allowed."),ok)}});
function loadProducts(){try{return JSON.parse(fs.readFileSync(PRODUCTS_FILE,"utf8"))}catch{return []}} function saveProducts(p){fs.writeFileSync(PRODUCTS_FILE,JSON.stringify(p,null,2))}
app.use((req,_res,next)=>{const raw=req.headers.cookie||"";req.cookies=Object.fromEntries(raw.split(";").filter(Boolean).map(x=>{const i=x.indexOf("=");return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1).trim())]}));next()});
function safeEqual(a,b){const aa=Buffer.from(String(a||"")),bb=Buffer.from(String(b||""));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb)} function setCookie(res,n,v){res.setHeader("Set-Cookie",`${n}=${encodeURIComponent(v)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`)} function clearCookie(res,n){res.setHeader("Set-Cookie",`${n}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`)}
function adminRequired(req,res,next){if(req.cookies.pd_admin==="1")return next();res.redirect("/admin/login")} function customerRequired(req,res,next){if(req.cookies.pd_customer==="1")return next();res.redirect(`/catalog/${encodeURIComponent(process.env.CUSTOMER_ACCESS_TOKEN||"")}/login`)}
app.get("/",(_r,res)=>res.render("home")); app.get("/admin/login",(_r,res)=>res.render("admin-login",{error:null}));
app.post("/admin/login",(req,res)=>{if(safeEqual(req.body.username,process.env.ADMIN_USERNAME)&&safeEqual(req.body.password,process.env.ADMIN_PASSWORD)){setCookie(res,"pd_admin","1");return res.redirect("/admin")}res.status(401).render("admin-login",{error:"Incorrect username or password."})});
app.post("/admin/logout",(_r,res)=>{clearCookie(res,"pd_admin");res.redirect("/")});
app.get("/admin",adminRequired,(req,res)=>res.render("admin",{products:loadProducts(),token:process.env.CUSTOMER_ACCESS_TOKEN||"",customerPasswordSet:Boolean(process.env.CUSTOMER_PASSWORD)}));
app.post("/admin/products",adminRequired,upload.single("image"),(req,res)=>{if(!req.file)return res.status(400).send("Product image is required.");const p=loadProducts();p.unshift({id:crypto.randomUUID(),code:(req.body.code||"").trim(),name:(req.body.name||"").trim(),metal:(req.body.metal||"").trim(),category:(req.body.category||"").trim(),image:`/product-image/${req.file.filename}`,createdAt:new Date().toISOString()});saveProducts(p);res.redirect("/admin")});
app.post("/admin/products/:id/delete",adminRequired,(req,res)=>{const p=loadProducts(),x=p.find(v=>v.id===req.params.id);if(x){const f=path.join(UPLOAD_DIR,path.basename(x.image||""));if(fs.existsSync(f))fs.unlinkSync(f)}saveProducts(p.filter(v=>v.id!==req.params.id));res.redirect("/admin")});
app.get("/product-image/:filename",(req,res)=>{if(req.cookies.pd_admin!=="1"&&req.cookies.pd_customer!=="1")return res.status(403).end();const f=path.join(UPLOAD_DIR,path.basename(req.params.filename));if(!fs.existsSync(f))return res.status(404).end();res.setHeader("Cache-Control","private,no-store,max-age=0");res.setHeader("Content-Disposition","inline");res.sendFile(f)});
app.get("/catalog/:token/login",(req,res)=>{if(!safeEqual(req.params.token,process.env.CUSTOMER_ACCESS_TOKEN))return res.status(404).send("Catalog not found.");res.render("customer-login",{token:req.params.token,error:null})});
app.post("/catalog/:token/login",(req,res)=>{if(!safeEqual(req.params.token,process.env.CUSTOMER_ACCESS_TOKEN))return res.status(404).send("Catalog not found.");if(safeEqual(req.body.password,process.env.CUSTOMER_PASSWORD)){setCookie(res,"pd_customer","1");return res.redirect(`/catalog/${encodeURIComponent(req.params.token)}`)}res.status(401).render("customer-login",{token:req.params.token,error:"Incorrect catalog password."})});
app.post("/catalog/logout",(_r,res)=>{clearCookie(res,"pd_customer");res.redirect("/")}); app.get("/catalog/:token",customerRequired,(req,res)=>{if(!safeEqual(req.params.token,process.env.CUSTOMER_ACCESS_TOKEN))return res.status(404).send("Catalog not found.");res.render("catalog",{products:loadProducts(),token:req.params.token})});
app.use((err,_r,res,_n)=>res.status(400).send(err.message||"Something went wrong."));
app.listen(PORT,"0.0.0.0",()=>console.log(`POOJA DIAMOND private catalog running on port ${PORT}`));